#ifndef ROBINLE_FONTFACE_DESIGNER_CONSTANTS
#define ROBINLE_FONTFACE_DESIGNER_CONSTANTS





#include <Windows.h>



constexpr UINT_PTR MENU_FILE = 0;
constexpr UINT_PTR MENU_FILE_NEW = MENU_FILE + 1;
constexpr UINT_PTR MENU_FILE_OPEN = MENU_FILE + 2;
constexpr UINT_PTR MENU_FILE_CLOSE = MENU_FILE + 3;
constexpr UINT_PTR MENU_FILE_SAVE = MENU_FILE + 4;
constexpr UINT_PTR MENU_FILE_SAVEAS = MENU_FILE + 5;
constexpr UINT_PTR MENU_FILE_EXIT = MENU_FILE + 6;

constexpr UINT_PTR MENU_EDIT = 10;
constexpr UINT_PTR MENU_EDIT_UNDO = MENU_EDIT + 1;
constexpr UINT_PTR MENU_EDIT_REDO = MENU_EDIT + 2;

constexpr UINT_PTR MENU_FONT = 20;
constexpr UINT_PTR MENU_FONT_PROPERTIES = MENU_FONT + 1;
constexpr UINT_PTR MENU_FONT_PREVIEW = MENU_FONT + 2;

constexpr UINT_PTR MENU_CHAR = 30;
constexpr UINT_PTR MENU_CHAR_ADD = MENU_CHAR + 1;
constexpr UINT_PTR MENU_CHAR_ADDCOPY = MENU_CHAR + 2;
constexpr UINT_PTR MENU_CHAR_SETWIDTH = MENU_CHAR + 3;
constexpr UINT_PTR MENU_CHAR_DELETE = MENU_CHAR + 4;

constexpr UINT_PTR MENU_VIEW = 40;
constexpr UINT_PTR MENU_VIEW_100PERCENT = MENU_VIEW + 1;


constexpr UINT_PTR MENU_HELP = 90;
constexpr UINT_PTR MENU_HELP_ABOUT = MENU_HELP + 1;
constexpr UINT_PTR MENU_HELP_WEBSITE = MENU_HELP + 2;
constexpr UINT_PTR MENU_HELP_GITHUB = MENU_HELP + 3;

constexpr int WIDTH_FORM_NEW = 500;
constexpr int HEIGHT_FORM_NEW = 200;





#endif // ROBINLE_FONTFACE_DESIGNER_CONSTANTS
